In [1]:
import pandas as pd

In [2]:
df_gender = pd.read_csv("./gender/all_people_with_manual_gender_merged.csv", dtype=str)

In [3]:
df_gender.head()

,movie_id,file,role,person_id,name,long_canonical_name,headshot,person,gender
0,2113683,4513_I_Know_That_Voice,cast,0012121,Charlie Adler,"Adler, Charlie",https://m.media-amazon.com/images/M/MV5BMjE0OT...,Charlie Adler,male
1,2113683,4513_I_Know_That_Voice,cast,0781899,Pamela Adlon,"Adlon, Pamela",https://m.media-amazon.com/images/M/MV5BMTc2OT...,Pamela Adlon,female
2,2113683,4513_I_Know_That_Voice,cast,0016141,Carlos Alazraqui,"Alazraqui, Carlos",https://m.media-amazon.com/images/M/MV5BMTQyMT...,Carlos Alazraqui,male
3,2113683,4513_I_Know_That_Voice,cast,0029460,Jack Angel,"Angel, Jack",https://m.media-amazon.com/images/M/MV5BNjM1Nz...,Jack Angel,male
4,2113683,4513_I_Know_That_Voice,cast,0000799,Edward Asner,"Asner, Edward",https://m.media-amazon.com/images/M/MV5BMTk0MD...,Edward Asner,male

In [4]:
df_eth = pd.read_csv("./support_crew/manual_crew/all_support_crew_with_ethnicity.csv", dtype={"movie_id": str, "person_id": str})

In [8]:
df_eth.head()

,movie_id,file,role,person_id,name,long_canonical_name,headshot,2PRACE,Hispanic,API,Black,AIAN,White,ethnicity
0,2113683,4513_I_Know_That_Voice,cast,0012121,Charlie Adler,"Adler, Charlie",https://m.media-amazon.com/images/M/MV5BMjE0OT...,0.000379,0.004028,0.002948,0.001485,0.000364,0.990795,White
1,2113683,4513_I_Know_That_Voice,cast,0781899,Pamela Adlon,"Adlon, Pamela",https://m.media-amazon.com/images/M/MV5BMTc2OT...,0.000162,0.008781,0.003106,0.013599,0.000527,0.973825,White
2,2113683,4513_I_Know_That_Voice,cast,0016141,Carlos Alazraqui,"Alazraqui, Carlos",https://m.media-amazon.com/images/M/MV5BMTQyMT...,0.000287,0.585044,0.009265,0.008217,0.000937,0.396249,Hispanic
3,2113683,4513_I_Know_That_Voice,cast,0029460,Jack Angel,"Angel, Jack",https://m.media-amazon.com/images/M/MV5BNjM1Nz...,0.000443,0.055670,0.009625,0.011204,0.001461,0.921597,White
4,2113683,4513_I_Know_That_Voice,cast,0000799,Edward Asner,"Asner, Edward",https://m.media-amazon.com/images/M/MV5BMTk0MD...,0.000061,0.002411,0.001585,0.003810,0.001658,0.990476,White

In [7]:
df_eth['ethnicity'] = df_eth[['2PRACE', 'Hispanic', 'API', 'Black', 'AIAN', 'White']].idxmax(axis=1)

In [15]:
is_same = df_gender['name'].equals(df_eth['name'])
print(is_same)

True

In [16]:
df_gender['ethnicity'] = df_eth['ethnicity']

In [17]:
df_gender

,movie_id,file,role,person_id,name,long_canonical_name,headshot,person,gender,ethnicity
0,2113683,4513_I_Know_That_Voice,cast,0012121,Charlie Adler,"Adler, Charlie",https://m.media-amazon.com/images/M/MV5BMjE0OT...,Charlie Adler,male,White
1,2113683,4513_I_Know_That_Voice,cast,0781899,Pamela Adlon,"Adlon, Pamela",https://m.media-amazon.com/images/M/MV5BMTc2OT...,Pamela Adlon,female,White
2,2113683,4513_I_Know_That_Voice,cast,0016141,Carlos Alazraqui,"Alazraqui, Carlos",https://m.media-amazon.com/images/M/MV5BMTQyMT...,Carlos Alazraqui,male,Hispanic
3,2113683,4513_I_Know_That_Voice,cast,0029460,Jack Angel,"Angel, Jack",https://m.media-amazon.com/images/M/MV5BNjM1Nz...,Jack Angel,male,White
4,2113683,4513_I_Know_That_Voice,cast,0000799,Edward Asner,"Asner, Edward",https://m.media-amazon.com/images/M/MV5BMTk0MD...,Edward Asner,male,White
...,...,...,...,...,...,...,...,...,...,...
644964,3726322,2580_It_Never_Sleeps,miscellaneous crew,9196204,Jon Anderson,"Anderson, Jon",NaN,NaN,male,White
644965,3726322,2580_It_Never_Sleeps,miscellaneous crew,5274081,Ric Crossley,"Crossley, Ric",NaN,NaN,male,White
644966,3726322,2580_It_Never_Sleeps,miscellaneous crew,6538683,Harry Gadd,"Gadd, Harry",NaN,NaN,male,White
644967,3726322,2580_It_Never_Sleeps,miscellaneous crew,6538684,Patricia Muckle,"Muckle, Patricia",NaN,NaN,female,White
644968,3726322,2580_It_Never_Sleeps,miscellaneous crew,2928951,George Tsikos,"Tsikos, George",NaN,NaN,male,White

In [18]:
df_gender.to_csv("all_crew_with_gender_ethnicity.csv", index=False)