### Merge Movies Metadata

Merge the movies metadata file with information on whether we have subtitles or screenplays for each of them.

In [9]:
import pandas as pd

In [10]:
df_x = pd.read_csv("../data/6_character_metadata/all_metadata_finalized.csv", dtype={"imdb_id": str})

In [11]:
df_x.columns

Index(['title', 'imdb_id', 'file', 'dir', 'synopsis', 'year', 'link'], dtype='object')

Read the file with metadata on screenplays

In [12]:
df_sc = pd.read_csv("../data/8_screenplays/3_character_matching/movies_with_high_coverage_and_matching/high_matches_meta.csv", dtype={"imdb_id": str})

In [13]:
df_sc.columns

Index(['imdb_id', 'title', 'sp_file', 'script_url'], dtype='object')

In [14]:
df_merged = df_x.merge(df_sc[["imdb_id", "sp_file"]], how="left", on="imdb_id")

In [19]:
df_merged[df_merged['imdb_id'].isnull()]

Empty DataFrame
Columns: [title, imdb_id, file, dir, synopsis, year, link, sp_file]
Index: []

In [19]:
# df_merged['imdb'] = ~df_merged['imdb'].isnull()
# df_merged = df_merged.rename(columns={"imdb": "screenplay", "filename": "screenplay_file"})

In [25]:
df_merged['screenplay'] = ~df_merged.sp_file.isnull()

In [26]:
df_merged[df_merged['screenplay']]

,title,imdb_id,file,dir,synopsis,year,link,sp_file,screenplay
49,The Lost City of Z,1212428,3388_The_Lost_City_of_Z,com,The Lost City of Z tells the incredible true s...,2017.0,/Lost-City-Z-Charlie-Hunnam/dp/B08J9C2J4T/ref=...,The-Lost-City-of-Z,True
55,One Night in Miami...,10612922,597_One_Night_in_Miami,com,One Night in Miami is a fictional account of o...,2021.0,/Night-Miami-Leslie-Kingsley-Ben-Adir/dp/B08NL...,One-Night-in-Miami,True
91,Case 39,0795351,5998_Case_39,com,Prompted to rescue ten-year-old Lillith Sulliv...,2010.0,/Case-39-Ren%C3%A9e-Zellweger/dp/B004I8YHOU/re...,Case-39,True
112,The Big Sick,5462602,6007_The_Big_Sick,com,The Big Sick is based on the real-life courtsh...,2017.0,/Big-Sick-Kumail-Nanjiani/dp/B089XXQ2T1/ref=sr...,Big-Sick-The,True
115,Hesher,1403177,6012_Hesher,com,A young boy has lost his mother and is losing ...,2011.0,/Hesher-Joseph-Gordon-Levitt/dp/B0B5NQ5N8D/ref...,Hesher,True
...,...,...,...,...,...,...,...,...,...
2777,The Woodsman,0361127,5524_The_Woodsman,com,A child molester returns to his hometown after...,2004.0,/Woodsman-Kevin-Bacon/dp/B0B5YD9CS7/ref=sr_1_7...,Woodsman-The,True
2804,Machine Gun Preacher,1586752,5554_Machine_Gun_Preacher,com,HD. Gerard Butler stars in this fact-based dra...,2011.0,/Machine-Gun-Preacher-Gerard-Butler/dp/B00845P...,Machine-Gun-Preacher,True
2811,The Lincoln Lawyer,1189340,906_The_Lincoln_Lawyer,in2010s,"A slick criminal defense attorney, Mick Haller...",2011.0,/Lincoln-Lawyer-4K-UHD/dp/B082FH357X/ref=sr_1_...,Lincoln-Lawyer-The,True
3094,Highlander: The Movie,0091203,4461_Highlander_The_Movie,com,An immortal Scottish swordsman must confront t...,1986.0,/Highlander-Movie-Christopher-Lambert/dp/B0094...,Highlander,True
3127,Sunshine Cleaning,0862846,2674_Sunshine_Cleaning,com,Former high school cheerleading captain Rose (...,2009.0,/Sunshine-Cleaning-Amy-Adams/dp/B008W028M8/ref...,Sunshine-Cleaning,True

Read the file with metadata on subtitles collected.

In [27]:
df_subtitles = pd.read_csv("../data/5_subtitles/subtitles_collected.csv")

In [28]:
df_subtitles.shape

(3576, 12)

In [29]:
df_subtitles.head()

,file,title,entityType,runtimeSeconds,synopsis,rating_count,rating,en_type,en_url,sdh_sub_lang,url,subtitle
0,0_My_Fault,My Fault,Movie,7056.0,"Noah must leave her town, boyfriend and friend...",817.0,4.7,subtitle,https://cf-timedtext.aux.pv-cdn.net/6d68/fe19/...,es-es,https://cf-timedtext.aux.pv-cdn.net/bdaf/38e0/...,SDH_EN
1,1000_On_The_Trail_of_UFOS_Dark_Sky,On The Trail of UFOS: Dark Sky,Movie,5123.0,On the Trail of UFOs: Dark Sky traces decades ...,408.0,3.7,sdh,https://cf-timedtext.aux.pv-cdn.net/463a/c028/...,en-us,https://cf-timedtext.aux.pv-cdn.net/463a/c028/...,SDH
2,1001_Student_Of_The_Year,Student Of The Year,Movie,8722.0,"Introducing Alia Bhatt (Sharanya Singhania), S...",60.0,3.7,subtitle,https://cf-timedtext.aux.pv-cdn.net/8a5a/ab97/...,NaN,NaN,EN
3,1005_The_Badge_The_Bible_and_Bigfoot,"The Badge, The Bible and Bigfoot",Movie,3971.0,"In a small coastal town Bigfoot is sighted, an...",69.0,2.8,sdh,https://cf-timedtext.aux.pv-cdn.net/ff4c/7b1e/...,en-us,https://cf-timedtext.aux.pv-cdn.net/ff4c/7b1e/...,SDH
4,1009_Sharknado_5_Global_Swarming,Sharknado 5: Global Swarming,Movie,5159.0,"With much of North America lying in ruins, the...",731.0,4.6,sdh,https://cf-timedtext.aux.pv-cdn.net/5d3d/ebe2/...,en-us,https://cf-timedtext.aux.pv-cdn.net/5d3d/ebe2/...,SDH

In [30]:
df_merge_with_sub = df_merged.merge(df_subtitles[["file", "subtitle"]], "left", on="file")

In [32]:
df_merge_with_sub.head()

,title,imdb_id,file,dir,synopsis,year,link,sp_file,screenplay,subtitle
0,My Fault,21909764,0_My_Fault,com,"Noah must leave her town, boyfriend and friend...",2023.0,/My-Fault-Nicole-Wallace/dp/B0B683GB78/ref=sr_...,NaN,False,SDH_EN
1,On The Trail of UFOS: Dark Sky,14928972,1000_On_The_Trail_of_UFOS_Dark_Sky,com,On the Trail of UFOs: Dark Sky traces decades ...,2021.0,/Trail-UFOS-Dark-Sky/dp/B09BKF2WGQ/ref=sr_1_24...,NaN,False,SDH
2,Student Of The Year,2172071,1001_Student_Of_The_Year,com,"Introducing Alia Bhatt (Sharanya Singhania), S...",2012.0,/Student-Year-Sidharth-Malhotra/dp/B0BZTD87WK/...,NaN,False,EN
3,"The Badge, The Bible and Bigfoot",11208026,1005_The_Badge_The_Bible_and_Bigfoot,com,"In a small coastal town Bigfoot is sighted, an...",2019.0,/Badge-Bible-Bigfoot-Ashley-Wright/dp/B09JMYV8...,NaN,False,SDH
4,Sharknado 5: Global Swarming,6298780,1009_Sharknado_5_Global_Swarming,com,"With much of North America lying in ruins, the...",2017.0,/Sharknado-Global-Swarming-Ian-Ziering/dp/B07M...,NaN,False,SDH

In [34]:
df_merge_with_sub[['title', 'imdb_id', 'file', 'dir', 'synopsis', 'year', 'link', 'screenplay', 'sp_file', 'subtitle']].to_csv("../data/8_screenplays/metadata_with_screenplay_subtitles.csv", index=False)